(defpackage #:cl-qwen/tests
  (:use #:cl #:fiveam)
  (:export #:run-tests))
(in-package #:cl-qwen/tests)
(def-suite qwen)
(in-suite qwen)
(defun fixture-path (name) (asdf:system-relative-pathname "cl-qwen" (concatenate 'string ".cache/fixtures/" name)))
(defun approximate (left right &optional (tolerance 0.0001))
  (<= (abs (- left right)) (* tolerance (+ 1.0 (abs right)))))
(defun float-vector (&rest values) (map 'cl-qwen::floats (lambda (x) (float x 1.0)) values))

(test gguf-validation
  (let ((file (cl-qwen/gguf:open-gguf (fixture-path "f32.gguf"))))
    (unwind-protect
         (progn (is (= 13 (hash-table-count (cl-qwen/gguf:gguf-tensors file))))
                (is (equal "qwen3" (gethash "general.architecture" (cl-qwen/gguf:gguf-metadata file)))))
      (cl-qwen/gguf:close-gguf file))
    (is (cl-qwen/gguf:gguf-closed-p file))
    (cl-qwen/gguf:close-gguf file))
  (dolist (name '("magic.gguf" "version.gguf" "truncated.gguf"))
    (signals cl-qwen/gguf:gguf-error (cl-qwen/gguf:open-gguf (fixture-path name)))))

(test numerical-stages
  (let ((x (float-vector -1000 0 1000)))
    (cl-qwen::silu! x)
    (is (= 0.0 (aref x 0))) (is (= 0.0 (aref x 1))) (is (= 1000.0 (aref x 2))))
  (let ((x (float-vector 1000 1001 1002)))
    (cl-qwen::softmax! x 3)
    (is (approximate (reduce #'+ x) 1.0))
    (is (approximate (aref x 2) (/ (exp 2d0) (+ 1d0 (exp 1d0) (exp 2d0))))))
  (let ((x (float-vector 3 4)) (out (cl-qwen::floats 2)))
    (cl-qwen::rmsnorm! out x (float-vector 1 2) 0.0)
    (is (approximate (aref out 0) (/ 3 (sqrt 12.5))))
    (is (approximate (aref out 1) (/ 8 (sqrt 12.5)))))
  (let ((x (float-vector 1 2 3 4)))
    (cl-qwen::rope! x 1 4 0 (float-vector 0 0) (float-vector 1 1))
    (is (equalp x (float-vector -3 -4 1 2))))
  (is (= 0 (cl-qwen::greedy-token (float-vector 3 3 2)))))

(test tokenizer
  (let ((model (cl-qwen:load-model (fixture-path "f32.gguf"))))
    (unwind-protect
         (progn
           (is (equalp #(257) (cl-qwen:tokenize model "abc")))
           (dolist (text (list "" "ab abc" "can't 123" "你好 👋 café" (format nil "a~%~%b  ")))
             (is (equal text (cl-qwen:detokenize model (cl-qwen:tokenize model text)))))
           (is (equalp #(259 257 260) (cl-qwen:tokenize model "<|im_start|>abc<|im_end|>" :special-tokens t)))
           (is (> (length (cl-qwen:tokenize model "<|im_end|>")) 1))
           (is (equal "" (cl-qwen:detokenize model #(260))))
           (is (equal "<|im_end|>" (cl-qwen:detokenize model #(260) :special-tokens t)))
           (signals error (cl-qwen:detokenize model #(-1)))
           (is (equal (cl-qwen:chat-prompt "hi")
                      (format nil "<|im_start|>user~%hi<|im_end|>~%<|im_start|>assistant~%<think>~%~%</think>~%~%"))))
      (cl-qwen:close-model model))))

(test independent-forward
  (dolist (format '("f32" "q8"))
    (let ((model (cl-qwen:load-model (fixture-path (concatenate 'string format ".gguf")))))
      (unwind-protect
           (let ((one (cl-qwen:make-session model :context-size 8))
                 (many (cl-qwen:make-session model :context-size 8 :workers 3)))
             (with-open-file (reference (fixture-path (concatenate 'string format ".logits"))
                                        :element-type '(unsigned-byte 8))
               (dolist (token '(97 98 99))
                 (let ((a (copy-seq (cl-qwen:step! one token))) (b (cl-qwen:step! many token)))
                   (dotimes (i (length a))
                     (is (approximate (aref a i) (aref b i) 0.000001))
                     (is (approximate (aref a i)
                                      (cl-qwen/gguf::float-value (cl-qwen/gguf::read-uint reference 4) nil)))))))
             (is (= 3 (cl-qwen:session-position one)))
             (cl-qwen:reset-session one)
             (is (= 0 (cl-qwen:session-position one)))
             (multiple-value-bind (a text) (cl-qwen:generate one "abc" :max-tokens 3)
               (declare (ignore text))
               (is (equalp a (cl-qwen:generate many "abc" :max-tokens 3)))
               (is (equalp a (cl-qwen:generate one "abc" :max-tokens 3))))
             (signals error (cl-qwen:step! one -1))
             (signals error (cl-qwen:generate one ""))
             (signals error (cl-qwen:generate one #(97 98) :max-tokens 20))
             (signals error (cl-qwen:generate one "abc" :system "bad"))
             (dotimes (i 8) (cl-qwen:step! (if (zerop i) (cl-qwen:reset-session one) one) 97))
             (signals error (cl-qwen:step! one 97))
             (cl-qwen:close-session one) (cl-qwen:close-session one)
             (signals error (cl-qwen:step! one 97))
             (cl-qwen:close-model model)
             (signals error (cl-qwen:step! many 97))
             (signals error (cl-qwen:make-session model)))
        (cl-qwen:close-model model)))))

(test worker-errors
  (let ((pool (cl-qwen::make-pool 3)))
    (unwind-protect
         (progn
           (signals error (cl-qwen::run-pool pool (lambda (id count) (declare (ignore count))
                                                   (when (= id 1) (error "worker failed")))))
           (let ((out (make-array 3 :initial-element 0)))
             (cl-qwen::run-pool pool (lambda (id count) (setf (aref out id) count)))
             (is (equalp #(3 3 3) out))))
      (cl-qwen::close-pool pool))))

(test malformed-models
  (dolist (name '("alignment" "architecture" "block-count" "head-size" "tokenizer" "duplicate" "encoding" "q8-width" "missing"))
    (signals error (cl-qwen:load-model (fixture-path (concatenate 'string name ".gguf"))))))

(test generation-boundaries
  (let ((model (cl-qwen:load-model (fixture-path "f32.gguf"))))
    (unwind-protect
         (let ((session (cl-qwen:make-session model :context-size 4)))
           (is (zerop (length (cl-qwen:generate session "abc" :max-tokens 0))))
           (is (= 1 (cl-qwen:session-position session)))
           (signals error (cl-qwen:make-session model :context-size 33))
           (signals error (cl-qwen:make-session model :workers 0))
           (let* ((predicted (aref (cl-qwen:generate session "abc" :max-tokens 1) 0))
                  (tokenizer (cl-qwen::model-tokenizer model)) (previous (cl-qwen::tokenizer-eos tokenizer)))
             (unwind-protect
                  (progn (setf (cl-qwen::tokenizer-eos tokenizer) (list predicted))
                         (is (zerop (length (cl-qwen:generate session "abc" :max-tokens 2)))))
               (setf (cl-qwen::tokenizer-eos tokenizer) previous))))
      (cl-qwen:close-model model))))

(test concurrent-closure
  (let* ((model (cl-qwen:load-model (fixture-path "f32.gguf")))
         (session (cl-qwen:make-session model :context-size 4 :workers 2))
         (gate (bt:make-lock)) (wake (bt:make-condition-variable))
         (entered nil) (release nil) (failure nil)
         (active (bt:make-thread
                  (lambda ()
                    (handler-case
                        (bt:with-lock-held ((cl-qwen::session-lock session))
                          (bt:with-lock-held (gate)
                            (setf entered t) (bt:condition-notify wake)
                            (loop until release do (bt:condition-wait wake gate)))
                          (cl-qwen::%step! session 97))
                      (error (c) (setf failure c)))))))
    (bt:with-lock-held (gate) (loop until entered do (bt:condition-wait wake gate)))
    (let ((closers (loop repeat 3 collect (bt:make-thread (lambda () (cl-qwen:close-model model))))))
      (loop repeat 1000 until (eq (cl-qwen::model-state model) :closing) do (sleep 0.001))
      (is (eq (cl-qwen::model-state model) :closing))
      (is (not (cl-qwen/gguf:gguf-closed-p (cl-qwen::model-mapping model))))
      (bt:with-lock-held (gate) (setf release t) (bt:condition-notify wake))
      (bt:join-thread active)
      (dolist (thread closers) (bt:join-thread thread))
      (is (null failure))
      (is (cl-qwen/gguf:gguf-closed-p (cl-qwen::model-mapping model)))
      (signals error (cl-qwen:reset-session session)))))

(defun run-tests ()
  (uiop:run-program (list "python3" (namestring (asdf:system-relative-pathname "cl-qwen" "tests/fixtures.py"))
                          (namestring (fixture-path ""))) :output *standard-output* :error-output *error-output*)
  (run! 'qwen))
