(load (merge-pathnames "bootstrap.lisp" *load-truename*))
(in-package #:cl-qwen)
(when (uiop:getenv "CL_QWEN_TRACE")
  (let ((directory (uiop:ensure-directory-pathname (uiop:getenv "CL_QWEN_TRACE"))))
    (setf *trace-stage*
          (lambda (name layer position values)
            (when (= position 1)
              (with-open-file (out (merge-pathnames (format nil "~A-~D.f32" name layer) directory)
                                   :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
                (sb-sys:with-pinned-objects (values)
                  (let ((ptr (sb-sys:vector-sap values)))
                    (dotimes (i (* 4 (length values))) (write-byte (sb-sys:sap-ref-8 ptr i) out))))))))))
(let* ((args (uiop:command-line-arguments))
       (model (load-model (first args)))
       (text (uiop:read-file-string (second args)))
       (special (string= (third args) "1"))
       (limit (parse-integer (fourth args)))
       (workers (if (sixth args) (parse-integer (sixth args)) 1))
       (tokens (tokenize model text :special-tokens special))
       (session (make-session model :context-size (max 256 (+ (length tokens) limit)) :workers workers :engine (intern (string-upcase (or (seventh args) "native")) :keyword))))
  (unwind-protect
       (with-open-file (out (fifth args) :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
         (format t "INPUT~{ ~D~}~%" (coerce tokens 'list))
         (labels ((record-step (token)
                    (let ((scores (step! session token)))
                      (sb-sys:with-pinned-objects (scores)
                        (let ((ptr (sb-sys:vector-sap scores)))
                          (dotimes (i (* 4 (length scores))) (write-byte (sb-sys:sap-ref-8 ptr i) out)))))))
           (map nil #'record-step tokens)
           (let ((generated nil))
             (dotimes (i limit)
               (let ((token (greedy-token (session-logits session))))
                 (when (member token (tokenizer-eos (model-tokenizer model))) (return))
                 (push token generated)
                 (when (< i (1- limit)) (record-step token))))
             (format t "OUTPUT~{ ~D~}~%" (nreverse generated)))))
    (close-model model)))
