(defpackage #:cl-qwen/gguf
  (:use #:cl)
  (:export #:open-gguf #:close-gguf #:gguf-metadata #:gguf-tensors #:gguf-closed-p
           #:tensor-name #:tensor-dimensions #:tensor-type #:tensor-bytes
           #:tensor-pointer #:gguf-error))
(in-package #:cl-qwen/gguf)

(define-condition gguf-error (error)
  ((reason :initarg :reason :reader gguf-error-reason))
  (:report (lambda (c stream) (write-string (gguf-error-reason c) stream))))
(defun invalid (format-string &rest args)
  (error 'gguf-error :reason (apply #'format nil format-string args)))

(defstruct tensor name dimensions type offset bytes pointer)
(defstruct (gguf (:constructor %make-gguf))
  metadata tensors pointer size (closed-p nil))

(cffi:defcfun ("open" posix-open) :int (path :string) (flags :int))
(cffi:defcfun ("close" posix-close) :int (fd :int))
(cffi:defcfun ("mmap" posix-mmap) :pointer
  (address :pointer) (length :size) (protection :int) (flags :int) (fd :int) (offset :int64))
(cffi:defcfun ("munmap" posix-munmap) :int (address :pointer) (length :size))

(defun read-uint (stream bytes)
  (let ((value 0))
    (dotimes (i bytes value)
      (let ((byte (read-byte stream nil nil)))
        (unless byte (invalid "Truncated GGUF at byte ~D" (file-position stream)))
        (setf (ldb (byte 8 (* 8 i)) value) byte)))))
(defun read-sint (stream bytes)
  (let* ((value (read-uint stream bytes)) (bits (* bytes 8)))
    (if (logbitp (1- bits) value) (- value (ash 1 bits)) value)))
(defun remaining (stream) (- (file-length stream) (file-position stream)))
(defun bounded-count (stream bytes)
  (let ((n (read-uint stream bytes)))
    (when (> n (remaining stream)) (invalid "Length ~D exceeds remaining file" n))
    n))
(defun read-string-value (stream)
  (let* ((n (bounded-count stream 8))
         (bytes (make-array n :element-type '(unsigned-byte 8))))
    (unless (= n (read-sequence bytes stream)) (invalid "Truncated string"))
    (handler-case (babel:octets-to-string bytes :encoding :utf-8 :errorp t)
      (error () (invalid "Invalid UTF-8 string")))))
(defun float-value (bits doublep)
  (cffi:with-foreign-object (ptr (if doublep :uint64 :uint32))
    (setf (cffi:mem-ref ptr (if doublep :uint64 :uint32)) bits)
    (cffi:mem-ref ptr (if doublep :double :float))))
(defun read-value (stream type &optional (depth 0))
  (when (> depth 32) (invalid "Metadata nesting exceeds 32 levels"))
  (case type
    (0 (read-uint stream 1)) (1 (read-sint stream 1))
    (2 (read-uint stream 2)) (3 (read-sint stream 2))
    (4 (read-uint stream 4)) (5 (read-sint stream 4))
    (6 (float-value (read-uint stream 4) nil))
    (7 (case (read-uint stream 1) (0 nil) (1 t) (t (invalid "Invalid boolean"))))
    (8 (read-string-value stream))
    (9 (let* ((element-type (read-uint stream 4)) (n (bounded-count stream 8))
              (out (make-array n)))
         (dotimes (i n out) (setf (aref out i) (read-value stream element-type (1+ depth))))))
    (10 (read-uint stream 8)) (11 (read-sint stream 8))
    (12 (float-value (read-uint stream 8) t))
    (t (invalid "Unknown metadata type ~D" type))))
(defun payload-bytes (type dims)
  (let ((elements (reduce #'* dims)))
    (case type
      (0 (* 4 elements)) ((1 30) (* 2 elements))
      (8 (unless (zerop (mod (aref dims 0) 32))
           (invalid "Q8_0 rows require whole 32-element blocks"))
         (* 34 (/ elements 32)))
      (t (invalid "Unsupported tensor type ~D" type)))))
(defun parse-gguf (stream)
  (unless (= (read-uint stream 4) #x46554747) (invalid "Invalid GGUF magic"))
  (unless (= (read-uint stream 4) 3) (invalid "Only little-endian GGUF v3 is supported"))
  (let* ((nt (bounded-count stream 8)) (nm (bounded-count stream 8))
         (metadata (make-hash-table :test 'equal)) (tensors (make-hash-table :test 'equal)))
    (dotimes (i nm)
      (let ((key (read-string-value stream)))
        (when (nth-value 1 (gethash key metadata)) (invalid "Duplicate metadata key ~A" key))
        (setf (gethash key metadata) (read-value stream (read-uint stream 4)))))
    (dotimes (i nt)
      (let* ((name (read-string-value stream)) (rank (read-uint stream 4)))
        (unless (<= 1 rank 4) (invalid "Invalid tensor rank ~D" rank))
        (when (gethash name tensors) (invalid "Duplicate tensor ~A" name))
        (let ((dims (make-array rank)))
          (dotimes (j rank)
            (let ((dim (read-uint stream 8)))
              (unless (<= 1 dim most-positive-fixnum) (invalid "Invalid tensor dimension ~D" dim))
              (setf (aref dims j) dim)))
          (let* ((type (read-uint stream 4)) (offset (read-uint stream 8))
                 (bytes (payload-bytes type dims)))
            (setf (gethash name tensors)
                  (make-tensor :name name :dimensions dims :type type :offset offset :bytes bytes))))))
    (let* ((alignment (gethash "general.alignment" metadata 32))
           (position (file-position stream)))
      (unless (and (integerp alignment) (<= 1 alignment 4096)
                   (zerop (logand alignment (1- alignment))))
        (invalid "Invalid tensor alignment ~A" alignment))
      (let ((data-start (* alignment (ceiling position alignment))) (end 0))
        (when (> data-start (file-length stream)) (invalid "Missing data section"))
        (dolist (tensor (sort (loop for x being the hash-values of tensors collect x) #'< :key #'tensor-offset))
          (let ((offset (tensor-offset tensor)))
            (unless (zerop (mod offset alignment)) (invalid "Unaligned tensor ~A" (tensor-name tensor)))
            (when (< offset end) (invalid "Overlapping tensor ~A" (tensor-name tensor)))
            (setf end (+ offset (tensor-bytes tensor)))
            (when (> (+ data-start end) (file-length stream))
              (invalid "Truncated tensor ~A" (tensor-name tensor)))))
        (values metadata tensors data-start)))))
(defun open-gguf (path)
  (let* ((path (truename path)) (size nil) (metadata nil) (tensors nil) (data-start nil))
    (with-open-file (stream path :element-type '(unsigned-byte 8))
      (setf size (file-length stream))
      (multiple-value-setq (metadata tensors data-start) (parse-gguf stream)))
    (let ((fd (posix-open (namestring path) 0)))
      (when (minusp fd) (invalid "Cannot open ~A" path))
      (unwind-protect
           (let ((pointer (posix-mmap (cffi:null-pointer) size 1 2 fd 0)))
             (when (= (cffi:pointer-address pointer) (1- (ash 1 (* 8 (cffi:foreign-type-size :pointer)))))
               (invalid "Cannot map ~A" path))
             (maphash (lambda (name tensor)
                        (declare (ignore name))
                        (setf (tensor-pointer tensor) (cffi:inc-pointer pointer (+ data-start (tensor-offset tensor)))))
                      tensors)
             (%make-gguf :metadata metadata :tensors tensors :pointer pointer :size size))
        (posix-close fd)))))
(defun close-gguf (gguf)
  (unless (gguf-closed-p gguf)
    (unless (zerop (posix-munmap (gguf-pointer gguf) (gguf-size gguf)))
      (invalid "Cannot unmap GGUF"))
    (setf (gguf-closed-p gguf) t)
    (maphash (lambda (name tensor) (declare (ignore name))
               (setf (tensor-pointer tensor) (cffi:null-pointer)))
             (gguf-tensors gguf)))
  (values))
