(in-package #:cl-qwen)

(trivial-simd:define-kernel float-row-dot (x weights)
  (trivial-simd:sum (* x weights)))
(trivial-simd:define-kernel q8-block-dot (x (weights :type :s8))
  (trivial-simd:sum (* x weights)))

(defun model-weights (model)
  (remove-duplicates
   (append (list (model-embedding model) (model-output model))
           (loop for layer across (model-layers model)
                 append (list (layer-q layer) (layer-k layer) (layer-v layer)
                              (layer-out layer) (layer-gate layer) (layer-up layer) (layer-down layer))))
   :test #'eq))
(defun prepare-kernel-weights (model)
  (dolist (weight (model-weights model))
    (when (and (eq (weight-encoding weight) :q8) (null (weight-quantized weight)))
      (let* ((n (* (weight-rows weight) (weight-columns weight)))
             (bytes (make-array n :element-type '(signed-byte 8))) (scales (floats (/ n 32))))
        (dotimes (block (/ n 32))
          (let ((pointer (cffi:inc-pointer (weight-storage weight) (* block 34))))
            (setf (aref scales block)
                  (half-float (logior (cffi:mem-aref pointer :uint8 0)
                                     (ash (cffi:mem-aref pointer :uint8 1) 8))))
            (dotimes (i 32)
              (setf (aref bytes (+ (* block 32) i)) (cffi:mem-aref pointer :int8 (+ i 2))))))
        (setf (weight-quantized weight) bytes (weight-scales weight) scales)))))
(defun quantize-activation! (input values scales)
  (declare (type floats input values scales) (optimize (speed 3)))
  (trivial-simd::with-single-float-bits (bits from-bits)
    (loop for start fixnum from 0 below (length input) by 32
          for block fixnum from 0
          do (let ((maximum 0.0))
               (declare (type single-float maximum))
               (dotimes (i 32)
                 (let ((x (aref input (+ start i))))
                   (when (= 255 (ldb (byte 8 23) (bits x)))
                     (error "Cannot quantize nonfinite Q8_0 activations"))
                   (setf maximum (max maximum (abs x)))))
               (let* ((scale (/ maximum 127.0))
                      (half (trivial-simd::f32-bits-to-f16 (bits scale) :nearest-even))
                      (inverse (if (zerop scale) 0.0
                                   (sb-int:with-float-traps-masked (:overflow :divide-by-zero)
                                     (/ 1.0 scale)))))
                 (when (= half #x7c00) (error "Q8_0 activation scale overflows F16"))
                 (setf (aref scales block) (half-float half))
                 (dotimes (i 32)
                   (let* ((x (aref input (+ start i)))
                          (scaled (if (= 255 (ldb (byte 8 23) (bits inverse)))
                                      (/ x scale) (* x inverse))))
                     (let ((byte (ldb (byte 8 0) (round scaled))))
                       (setf (aref values (+ start i))
                             (float (if (< byte 128) byte (- byte 256)) 1.0)))))))))
  values)
(defun kernel-float-matvec (weight input output pool)
  (each-row-range
   pool (weight-rows weight)
   (lambda (start rows)
     (float-row-dot input (weight-storage weight) :rows rows :row-length (weight-columns weight)
                    :x-row-stride 0 :weights-start (* start (weight-columns weight))
                    :destination output :destination-start start))))
(defun kernel-q8-matvec (weight input output session)
  (let* ((columns (weight-columns weight)) (blocks (/ columns 32))
         (activation (session-activation session)) (scales (session-activation-scales session))
         (bytes (weight-quantized weight)))
    (quantize-activation! input activation scales)
    ;; Parallel FILL slices can share a machine word at their boundaries.
    (fill output 0.0)
    (sb-sys:with-pinned-objects (activation bytes output)
      (run-pool
       (session-pool session)
       (lambda (id count)
         (let* ((start (floor (* (weight-rows weight) id) count))
                (end (floor (* (weight-rows weight) (1+ id)) count))
                (dots (aref (session-block-results session) id)))
           (dotimes (block blocks)
             (q8-block-dot activation bytes :rows (- end start) :row-length 32
                           :x-start (* block 32) :x-row-stride 0
                           :weights-start (+ (* start columns) (* block 32))
                           :weights-row-stride columns :destination dots)
             (loop for row fixnum from start below end
                   for index fixnum from 0
                   do (setf (aref output row)
                            (trivial-simd:fma
                             (aref dots index)
                             (* (aref (weight-scales weight) (+ (* row blocks) block))
                                (aref scales block))
                             (aref output row)))))))))))
