(in-package #:cl-qwen)

(defstruct layer attn-norm q k v out q-norm k-norm ffn-norm gate up down)
(defstruct (model (:constructor %make-model))
  mapping metadata tokenizer layers embedding output output-norm
  hidden ff heads kv-heads head-size context epsilon theta
  (lock (bt:make-lock "model lifetime")) (closed (bt:make-condition-variable))
  (state :open) (sessions nil))
(defun ensure-model-open (model)
  (unless (eq (model-state model) :open) (error "Model is closing or closed")))
(defun metadata-number (metadata key &optional default)
  (let ((value (gethash key metadata default)))
    (unless (and (realp value) (> value 0)) (error "Missing or invalid ~A" key))
    value))
(defun metadata-integer (metadata key &optional default)
  (let ((value (metadata-number metadata key default)))
    (unless (and (integerp value) (<= value most-positive-fixnum)) (error "Invalid dimension ~A" key))
    value))
(defun tensor-weight (tensor)
  (let* ((dims (cl-qwen/gguf:tensor-dimensions tensor)) (columns (aref dims 0))
         (rows (if (= (length dims) 1) 1 (aref dims 1)))
         (type (cl-qwen/gguf:tensor-type tensor)) (ptr (cl-qwen/gguf:tensor-pointer tensor)))
    (case type
      (0 (make-weight :columns columns :rows rows :encoding :f32
                      :storage (trivial-simd:make-vector-view ptr :f32 (* rows columns))))
      ((1 30)
       (let ((values (floats (* rows columns))))
         (trivial-simd:convert! values (trivial-simd:make-vector-view ptr :u16 (* rows columns))
                               :input-encoding (if (= type 1) :f16 :bf16))
         (make-weight :columns columns :rows rows :encoding :f32 :storage values)))
      (8 (ensure-native) (make-weight :columns columns :rows rows :encoding :q8 :storage ptr)))))
(defun load-model (path)
  (let ((mapping (cl-qwen/gguf:open-gguf path)) (success nil))
    (unwind-protect
         (let* ((metadata (cl-qwen/gguf:gguf-metadata mapping))
                (tensors (cl-qwen/gguf:gguf-tensors mapping)))
           (unless (equal (gethash "general.architecture" metadata) "qwen3")
             (error "Only the dense Qwen3 architecture is supported"))
           (unless (and (zerop (gethash "qwen3.expert_count" metadata 0))
                        (equal (gethash "qwen3.rope.scaling.type" metadata "none") "none"))
             (error "Experts and scaled RoPE are unsupported"))
           (let* ((hidden (metadata-integer metadata "qwen3.embedding_length"))
                  (ff (metadata-integer metadata "qwen3.feed_forward_length"))
                  (heads (metadata-integer metadata "qwen3.attention.head_count"))
                  (kv-heads (metadata-integer metadata "qwen3.attention.head_count_kv"))
                  (head-size (metadata-integer metadata "qwen3.attention.key_length"))
                  (n-layer (metadata-integer metadata "qwen3.block_count"))
                  (context (metadata-integer metadata "qwen3.context_length"))
                  (epsilon (float (metadata-number metadata "qwen3.attention.layer_norm_rms_epsilon") 1.0))
                  (theta (float (metadata-number metadata "qwen3.rope.freq_base" 1000000.0) 1.0))
                  (tokenizer (build-tokenizer metadata))
                  (vocabulary (length (tokenizer-tokens tokenizer)))
                  (layers (progn
                            (unless (<= n-layer (floor (- (hash-table-count tensors) 2) 11))
                              (error "Block count exceeds available tensors"))
                            (make-array n-layer))))
             (unless (and (zerop (mod heads kv-heads)) (evenp head-size)
                          (= head-size (metadata-integer metadata "qwen3.attention.value_length" head-size))
                          (= head-size (metadata-integer metadata "qwen3.rope.dimension_count" head-size)))
               (error "Unsupported Qwen3 head or rotary dimensions"))
             (labels ((required (name dims)
                        (let ((tensor (gethash name tensors)))
                          (unless (and tensor (equalp (cl-qwen/gguf:tensor-dimensions tensor) dims))
                            (error "Missing or incorrectly shaped tensor ~A (expected ~S)" name dims))
                          (tensor-weight tensor)))
                      (norm (name n)
                        (let* ((weight (required name (vector n))) (values (floats n)))
                          (weight-row! weight 0 values)
                          values)))
               (dotimes (i n-layer)
                 (flet ((name (suffix) (format nil "blk.~D.~A.weight" i suffix)))
                   (setf (aref layers i)
                         (make-layer
                          :attn-norm (norm (name "attn_norm") hidden)
                          :q (required (name "attn_q") (vector hidden (* heads head-size)))
                          :k (required (name "attn_k") (vector hidden (* kv-heads head-size)))
                          :v (required (name "attn_v") (vector hidden (* kv-heads head-size)))
                          :out (required (name "attn_output") (vector (* heads head-size) hidden))
                          :q-norm (norm (name "attn_q_norm") head-size)
                          :k-norm (norm (name "attn_k_norm") head-size)
                          :ffn-norm (norm (name "ffn_norm") hidden)
                          :gate (required (name "ffn_gate") (vector hidden ff))
                          :up (required (name "ffn_up") (vector hidden ff))
                          :down (required (name "ffn_down") (vector ff hidden))))))
               (let* ((embedding (required "token_embd.weight" (vector hidden vocabulary)))
                      (output (if (gethash "output.weight" tensors)
                                  (required "output.weight" (vector hidden vocabulary)) embedding))
                      (model (%make-model
                              :mapping mapping :metadata metadata :tokenizer tokenizer
                              :layers layers :embedding embedding :output output
                              :output-norm (norm "output_norm.weight" hidden)
                              :hidden hidden :ff ff :heads heads :kv-heads kv-heads :head-size head-size
                              :context context :epsilon epsilon :theta theta)))
                 (setf success t)
                 model))))
      (unless success (cl-qwen/gguf:close-gguf mapping)))))
(defun close-model (model)
  (let ((sessions nil))
    (bt:with-lock-held ((model-lock model))
      (loop while (eq (model-state model) :closing)
            do (bt:condition-wait (model-closed model) (model-lock model)))
      (when (eq (model-state model) :closed)
        (bt:condition-notify (model-closed model))
        (return-from close-model (values)))
      (setf (model-state model) :closing sessions (copy-list (model-sessions model))))
    (unwind-protect
         (progn
           (dolist (session sessions) (close-session session))
           (cl-qwen/gguf:close-gguf (model-mapping model)))
      (bt:with-lock-held ((model-lock model))
        (setf (model-state model) :closed (model-sessions model) nil)
        (bt:condition-notify (model-closed model)))))
  (values))
(defun tokenize (model text &key special-tokens)
  (bt:with-lock-held ((model-lock model))
    (ensure-model-open model)
    (tokenize-with (model-tokenizer model) text special-tokens)))
(defun detokenize (model ids &key special-tokens)
  (bt:with-lock-held ((model-lock model))
    (ensure-model-open model)
    (detokenize-with (model-tokenizer model) ids special-tokens)))
