(in-package #:cl-qwen)

(deftype floats () '(simple-array single-float (*)))
(defun floats (n) (make-array n :element-type 'single-float :initial-element 0.0))
(defstruct weight storage (columns 0 :type fixnum) (rows 0 :type fixnum) encoding quantized scales)
(cffi:define-foreign-library qwen-numeric
  (:darwin (:or "libcl_qwen_numeric.dylib"))
  (:unix (:or "libcl_qwen_numeric.so")))
(defvar *native-loaded* nil)
(defvar *native-lock* (bt:make-lock "numerical library initialization"))
(defun ensure-native ()
  (unless *native-loaded*
    (bt:with-lock-held (*native-lock*)
      (unless *native-loaded*
        (let ((path (asdf:system-relative-pathname "cl-qwen" "build/")))
          (let ((cffi:*foreign-library-directories* (cons path cffi:*foreign-library-directories*)))
            (cffi:use-foreign-library qwen-numeric)))
        (setf *native-loaded* t)))))
(cffi:defcfun ("cq_q8_matvec" q8-matvec) :int
  (blocks :pointer) (x :pointer) (out :pointer) (rows :size) (width :size))
(cffi:defcfun ("cq_q8_pack" %q8-pack) :int (x :pointer) (blocks :pointer) (width :size))

(defun q8-pack (input packed width)
  ;; Optimized C may evaluate discarded divisions for zero/subnormal blocks.
  (sb-int:with-float-traps-masked (:invalid :overflow :divide-by-zero)
    (%q8-pack input packed width)))

(defstruct (pool (:constructor %make-pool))
  (lock (bt:make-lock "matvec pool")) (wake (bt:make-condition-variable))
  (done (bt:make-condition-variable)) (threads nil) (generation 0) (finished 0)
  job errors (stopped nil))
(defun pool-worker (pool id)
  (let ((seen 0))
    (loop
      (let ((job
              (bt:with-lock-held ((pool-lock pool))
                (loop while (and (not (pool-stopped pool)) (= seen (pool-generation pool)))
                      do (bt:condition-wait (pool-wake pool) (pool-lock pool)))
                (when (pool-stopped pool) (return-from pool-worker))
                (setf seen (pool-generation pool))
                (pool-job pool))))
        (handler-case (funcall job id)
          (error (c) (setf (aref (pool-errors pool) id) c)))
        (bt:with-lock-held ((pool-lock pool))
          (incf (pool-finished pool))
          (bt:condition-notify (pool-done pool)))))))
(defun make-pool (count)
  (unless (and (integerp count) (<= 1 count 256)) (error "Worker count must be 1..256"))
  (let ((pool (%make-pool :errors (make-array count :initial-element nil))))
    (when (> count 1)
      (handler-case
          (dotimes (i count)
            (let ((id i))
              (push (bt:make-thread (lambda () (pool-worker pool id)) :name "cl-qwen matvec")
                    (pool-threads pool))))
        (error (c) (close-pool pool) (error c))))
    pool))
(defun close-pool (pool)
  (when pool
    (bt:with-lock-held ((pool-lock pool))
      (setf (pool-stopped pool) t)
      (dotimes (i (length (pool-threads pool))) (bt:condition-notify (pool-wake pool))))
    (dolist (thread (pool-threads pool)) (bt:join-thread thread))
    (setf (pool-threads pool) nil)))
(defun run-pool (pool function)
  (if (null (pool-threads pool))
      (funcall function 0 1)
      (let ((count (length (pool-threads pool)))
            (backend trivial-simd::*backend*) (fma-mode trivial-simd::*fma-mode*))
        (bt:with-lock-held ((pool-lock pool))
          (fill (pool-errors pool) nil)
          (setf (pool-finished pool) 0
                (pool-job pool) (lambda (i)
                                 (let ((trivial-simd::*backend* backend)
                                       (trivial-simd::*fma-mode* fma-mode))
                                   (funcall function i count))))
          (incf (pool-generation pool))
          (dotimes (i count) (bt:condition-notify (pool-wake pool)))
          (loop until (= (pool-finished pool) count)
                do (bt:condition-wait (pool-done pool) (pool-lock pool)))
          (setf (pool-job pool) nil)
          (let ((error (find-if #'identity (pool-errors pool))))
            (when error (error error)))))))
(defun each-row-range (pool rows function)
  (flet ((work (id count)
           (let ((start (floor (* rows id) count)) (end (floor (* rows (1+ id)) count)))
             (when (< start end) (funcall function start (- end start))))))
    (if pool (run-pool pool #'work) (work 0 1))))
(defun float-matvec (weight input output pool)
  (each-row-range
   pool (weight-rows weight)
   (lambda (start rows)
     (let ((view (trivial-simd/blas:make-matrix-view
                  (weight-storage weight) rows (weight-columns weight)
                  :offset (* start (weight-columns weight)))))
       (trivial-simd/blas:sgemv :no-transpose 1.0 view input 1 0.0 output 1 :y-offset start)))))
(defun packed-matvec (weight input output pool packed)
  (ensure-native)
  (let* ((columns (weight-columns weight)) (row-bytes (* (/ columns 32) 34))
         (packed (or packed (make-array row-bytes :element-type '(unsigned-byte 8)))))
    (unless (>= (length packed) row-bytes) (error "Q8_0 scratch is too short"))
    (sb-sys:with-pinned-objects (input output packed)
      (let ((x (sb-sys:vector-sap packed)) (out (sb-sys:vector-sap output)))
        (unless (zerop (q8-pack (sb-sys:vector-sap input) x columns))
          (error "Cannot quantize nonfinite or overflowing Q8_0 activations"))
        (each-row-range
         pool (weight-rows weight)
         (lambda (start rows)
           (unless (zerop (q8-matvec (cffi:inc-pointer (weight-storage weight) (* start row-bytes))
                                    x (cffi:inc-pointer out (* start 4)) rows columns))
             (error "Native Q8_0 matvec rejected dimensions"))))))))
(defun matvec (weight input output &optional pool packed session)
  (check-type input floats) (check-type output floats)
  (unless (and (= (length input) (weight-columns weight)) (= (length output) (weight-rows weight)))
    (error "Matvec dimensions do not match"))
  (when (eq input output) (error "Matvec input and output must be distinct"))
  (ecase (weight-encoding weight)
    (:f32 (if (and session (eq (session-engine session) :lisp))
              (kernel-float-matvec weight input output pool)
              (float-matvec weight input output pool)))
    (:q8 (if (and session (not (eq (session-engine session) :native)))
             (kernel-q8-matvec weight input output session)
             (packed-matvec weight input output pool packed))))
  output)
(defun half-float (bits)
  (let ((sign (if (logbitp 15 bits) -1.0 1.0)) (exponent (ldb (byte 5 10) bits))
        (fraction (ldb (byte 10 0) bits)))
    (when (= exponent 31) (error "Nonfinite Q8_0 scale"))
    (* sign (if (zerop exponent) (scale-float (float fraction 1.0) -24)
                (scale-float (+ 1.0 (/ fraction 1024.0)) (- exponent 15))))))
(defun weight-row! (weight row out)
  (let ((columns (weight-columns weight)))
    (unless (and (<= 0 row) (< row (weight-rows weight)) (= (length out) columns))
      (error "Invalid embedding row"))
    (ecase (weight-encoding weight)
      (:f32 (trivial-simd:copy! out (weight-storage weight) :source-start (* row columns) :end columns))
      (:q8
       (let ((ptr (cffi:inc-pointer (weight-storage weight) (* row (/ columns 32) 34))))
         (loop for col from 0 below columns by 32 for block from 0
               for address = (cffi:inc-pointer ptr (* block 34))
               for scale = (half-float (logior (cffi:mem-aref address :uint8 0)
                                               (ash (cffi:mem-aref address :uint8 1) 8)))
               do (dotimes (i 32)
                    (setf (aref out (+ col i)) (* scale (cffi:mem-aref address :int8 (+ i 2))))))))))
  out)
(defun rmsnorm! (out input weights epsilon &key (start 0) (size (length input)))
  (declare (type floats out input weights) (type fixnum start size) (type single-float epsilon)
           (optimize (speed 3)))
  (let ((sum 0d0))
    (declare (type double-float sum))
    (dotimes (i size)
      (let ((x (aref input (+ start i))))
        (incf sum (float (* x x) 1d0))))
    (let ((scale (/ 1.0 (sqrt (+ epsilon (float (/ sum size) 1.0))))))
      (declare (type single-float scale))
      (dotimes (i size out)
        (setf (aref out (+ start i)) (* (aref input (+ start i)) scale (aref weights i)))))))
(defun four-lane-dot (left right left-start right-start n)
  (declare (type floats left right) (type fixnum left-start right-start n)
           (optimize (speed 3)))
  (let ((a 0.0) (b 0.0) (c 0.0) (d 0.0) (sum 0.0)
        (limit (* 4 (floor n 4))))
    (declare (type single-float a b c d sum) (type fixnum limit))
    (loop for i fixnum from 0 below limit by 4
          for l fixnum = (+ left-start i) for r fixnum = (+ right-start i)
          do (incf a (* (aref left l) (aref right r)))
             (incf b (* (aref left (+ l 1)) (aref right (+ r 1))))
             (incf c (* (aref left (+ l 2)) (aref right (+ r 2))))
             (incf d (* (aref left (+ l 3)) (aref right (+ r 3)))))
    (incf sum a) (incf sum b) (incf sum c) (incf sum d)
    (loop for i fixnum from limit below n
          do (incf sum (* (aref left (+ left-start i)) (aref right (+ right-start i)))))
    sum))

(defun softmax! (values n)
  (declare (type floats values) (type fixnum n) (optimize (speed 3)))
  (unless (<= 1 n (length values)) (error "Invalid softmax length"))
  (let ((maximum (trivial-simd:maximum values :end n)) (sum 0d0))
    (declare (type single-float maximum) (type double-float sum))
    (dotimes (i n)
      (let ((value (exp (- (aref values i) maximum))))
        (setf (aref values i) value)
        (incf sum (float value 1d0))))
    (let ((inverse (float (/ 1d0 sum) 1.0)))
      (dotimes (i n values) (setf (aref values i) (* (aref values i) inverse))))))
(defun silu! (values)
  (declare (type floats values) (optimize (speed 3)))
  (dotimes (i (length values) values)
    (let ((x (aref values i)))
      (setf (aref values i)
            (if (< x -80.0) (let ((e (exp x))) (* x (/ e (+ 1.0 e))))
                (/ x (+ 1.0 (exp (- x)))))))))
