(in-package #:cl-qwen)

(defstruct (session (:constructor %make-session))
  model context pool (engine :native :read-only t) (backend nil :read-only t)
  block-results activation activation-scales
  (lock (bt:make-lock "inference session")) (closed-p nil) (position 0)
  keys values cosines sines packed x normalized q k v attention temporary gate up scores logits)
(defun ensure-session-open (session &optional allow-closing)
  (when (session-closed-p session) (error "Session is closed"))
  (unless (and allow-closing (eq (model-state (session-model session)) :closing))
    (ensure-model-open (session-model session))))
(defun make-session (model &key (context-size 2048) (workers 1) (engine :native))
  (unless (and (integerp workers) (<= 1 workers 256)) (error "Worker count must be 1..256"))
  (unless (member engine '(:native :kernel :lisp)) (error "Unknown engine ~S" engine))
  (bt:with-lock-held ((model-lock model))
    (ensure-model-open model)
    (unless (and (integerp context-size) (<= 1 context-size (model-context model)))
      (error "Context size must be 1..~D" (model-context model)))
    (let* ((hidden (model-hidden model)) (head-size (model-head-size model))
           (width (* (model-kv-heads model) head-size)) (q-width (* (model-heads model) head-size))
           (layers (length (model-layers model))) (half (/ head-size 2))
           (weights (model-weights model))
           (cosines (floats (* context-size half))) (sines (floats (* context-size half))))
      (let ((theta-scale (expt (model-theta model) (/ -2.0 head-size))))
        (dotimes (position context-size)
          (let ((angle (float position 1.0)))
            (dotimes (i half)
              (let ((offset (+ (* position half) i)))
                (setf (aref cosines offset) (cos angle) (aref sines offset) (sin angle)))
              (setf angle (* angle theta-scale))))))
      (unless (eq engine :native) (prepare-kernel-weights model))
      (when (and (eq engine :native) (find :q8 weights :key #'weight-encoding))
        (ensure-native))
      (let ((session (%make-session
                      :model model :engine engine :backend (if (eq engine :lisp) :lisp (trivial-simd:backend))
                      :context context-size :cosines cosines :sines sines
                      :keys (map 'vector (lambda (x) (declare (ignore x)) (floats (* context-size width)))
                                 (make-array layers))
                      :values (map 'vector (lambda (x) (declare (ignore x)) (floats (* context-size width)))
                                   (make-array layers))
                      :packed (make-array (* (ceiling (max hidden (model-ff model) q-width) 32) 34)
                                          :element-type '(unsigned-byte 8))
                      :x (floats hidden) :normalized (floats hidden) :temporary (floats hidden)
                      :q (floats q-width) :k (floats width) :v (floats width) :attention (floats q-width)
                      :gate (floats (model-ff model)) :up (floats (model-ff model))
                      :scores (floats context-size) :logits (floats (weight-rows (model-output model))))))
        (when (and (not (eq engine :native)) (find :q8 weights :key #'weight-encoding))
          (let* ((width (max hidden (model-ff model) q-width))
                 (capacity (loop for weight in weights
                                 maximize (ceiling (weight-rows weight) workers))))
            (setf (session-activation session) (floats width)
                  (session-activation-scales session) (floats (ceiling width 32))
                  (session-block-results session)
                  (map 'vector (lambda (i) (declare (ignore i)) (floats capacity))
                       (make-array workers)))))
        (setf (session-pool session) (make-pool workers))
        (push session (model-sessions model))
        session))))
(defun close-session (session)
  (bt:with-lock-held ((session-lock session))
    (unless (session-closed-p session)
      (close-pool (session-pool session))
      (setf (session-closed-p session) t)
      (let ((model (session-model session)))
        (bt:with-lock-held ((model-lock model))
          (setf (model-sessions model) (delete session (model-sessions model)))))
      (setf (session-keys session) nil (session-values session) nil
            (session-cosines session) nil (session-sines session) nil
            (session-block-results session) nil (session-activation session) nil
            (session-activation-scales session) nil)))
  (values))
(defun %reset-session (session)
  (ensure-session-open session t)
  (setf (session-position session) 0)
  session)
(defun reset-session (session)
  (bt:with-lock-held ((session-lock session))
    (ensure-session-open session)
    (%reset-session session)))
(defun rope! (values heads head-size position cosines sines)
  (declare (type floats values cosines sines) (type fixnum heads head-size position) (optimize (speed 3)))
  (let* ((half (floor head-size 2)) (table (* position half)))
    (dotimes (head heads values)
      (let ((offset (* head head-size)))
        (dotimes (i half)
          (let* ((a (+ offset i)) (b (+ a half)) (x (aref values a)) (y (aref values b))
                 (cosine (aref cosines (+ table i))) (sine (aref sines (+ table i))))
            (setf (aref values a) (trivial-simd:fma x cosine (- (* y sine)))
                  (aref values b) (trivial-simd:fma x sine (* y cosine)))))))))
;; TODO (#133): per-position dot dispatch allocates; batch attention rows.
(defun attention! (session layer-index)
  (let* ((model (session-model session)) (heads (model-heads model)) (kv-heads (model-kv-heads model))
         (head-size (model-head-size model)) (kv-width (* kv-heads head-size))
         (position (session-position session)) (n (1+ position))
         (keys (aref (session-keys session) layer-index)) (values (aref (session-values session) layer-index))
         (q (session-q session)) (out (session-attention session)) (scores (session-scores session))
         (scale (/ 1.0 (sqrt (float head-size 1.0)))))
    (declare (type floats keys values q out scores) (type fixnum heads kv-heads head-size kv-width position n)
             (type single-float scale) (optimize (speed 3)))
    (trivial-simd:copy! keys (session-k session) :destination-start (* position kv-width) :end kv-width)
    (trivial-simd:copy! values (session-v session) :destination-start (* position kv-width) :end kv-width)
    (dotimes (head heads)
      (let ((q-start (* head head-size)) (kv-start (* (floor head (/ heads kv-heads)) head-size)))
        (dotimes (i n)
          (setf (aref scores i)
                (* scale (if (eq (session-backend session) :lisp)
                             (four-lane-dot q keys q-start (+ (* i kv-width) kv-start) head-size)
                             (trivial-simd:dot q keys :left-start q-start
                                               :right-start (+ (* i kv-width) kv-start) :end head-size)))))
        (softmax! scores n)
        (dotimes (j head-size)
          (let ((sum 0.0))
            (declare (type single-float sum))
            (dotimes (i n) (incf sum (* (aref scores i) (aref values (+ (* i kv-width) kv-start j)))))
            (setf (aref out (+ q-start j)) sum)))))
    out))
(defvar *trace-stage* nil)
(declaim (inline trace-stage))
(defun trace-stage (name layer position values)
  (when *trace-stage* (funcall *trace-stage* name layer position values)))
(defun %step! (session token)
  (let ((trivial-simd::*backend* (session-backend session))
        (trivial-simd::*fma-mode* (if (eq (session-engine session) :lisp)
                                    (if trivial-simd::*arm64-fma-available-p* :in-process :portable)
                                    trivial-simd::*fma-mode*)))
    (%engine-step! session token)))
(defun %engine-step! (session token)
  (ensure-session-open session t)
  (let* ((model (session-model session)) (position (session-position session))
         (hidden (model-hidden model)) (head-size (model-head-size model))
         (x (session-x session)) (normalized (session-normalized session))
         (q (session-q session)) (k (session-k session)) (pool (session-pool session)) (packed (session-packed session)))
    (unless (and (integerp token) (<= 0 token) (< token (weight-rows (model-embedding model))))
      (error "Invalid token ID ~A" token))
    (when (>= position (session-context session)) (error "Context is full; reset or create a larger session"))
    (weight-row! (model-embedding model) token x)
    (dotimes (i (length (model-layers model)))
      (let ((layer (aref (model-layers model) i)))
        (rmsnorm! normalized x (layer-attn-norm layer) (model-epsilon model) :size hidden)
        (trace-stage "attn_norm" i position normalized)
        (matvec (layer-q layer) normalized q pool packed session)
        (matvec (layer-k layer) normalized k pool packed session)
        (matvec (layer-v layer) normalized (session-v session) pool packed session)
        (dotimes (head (model-heads model))
          (rmsnorm! q q (layer-q-norm layer) (model-epsilon model) :start (* head head-size) :size head-size))
        (dotimes (head (model-kv-heads model))
          (rmsnorm! k k (layer-k-norm layer) (model-epsilon model) :start (* head head-size) :size head-size))
        (trace-stage "Qcur_normed" i position q)
        (trace-stage "Kcur_normed" i position k)
        (rope! q (model-heads model) head-size position (session-cosines session) (session-sines session))
        (rope! k (model-kv-heads model) head-size position (session-cosines session) (session-sines session))
        (trace-stage "Qcur" i position q)
        (trace-stage "Kcur" i position k)
        (trace-stage "Vcur" i position (session-v session))
        (attention! session i)
        (trace-stage "attn_head_output" i position (session-attention session))
        (matvec (layer-out layer) (session-attention session) (session-temporary session) pool packed session)
        (trace-stage "attn_out" i position (session-temporary session))
        (trivial-simd:add! x x (session-temporary session))
        (trace-stage "ffn_inp" i position x)
        (rmsnorm! normalized x (layer-ffn-norm layer) (model-epsilon model) :size hidden)
        (trace-stage "ffn_norm" i position normalized)
        (matvec (layer-gate layer) normalized (session-gate session) pool packed session)
        (matvec (layer-up layer) normalized (session-up session) pool packed session)
        (trace-stage "ffn_gate" i position (session-gate session))
        (trace-stage "ffn_up" i position (session-up session))
        (silu! (session-gate session))
        (trivial-simd:multiply! (session-gate session) (session-gate session) (session-up session))
        (matvec (layer-down layer) (session-gate session) (session-temporary session) pool packed session)
        (trace-stage "ffn_out" i position (session-temporary session))
        (trivial-simd:add! x x (session-temporary session))
        (trace-stage "l_out" i position x)))
    (rmsnorm! normalized x (model-output-norm model) (model-epsilon model) :size hidden)
    (matvec (model-output model) normalized (session-logits session) pool packed session)
    (incf (session-position session))
    (session-logits session)))
(defun step! (session token)
  (bt:with-lock-held ((session-lock session))
    (ensure-session-open session)
    (%step! session token)))
(defun greedy-token (logits)
  (declare (type floats logits) (optimize (speed 3)))
  (let ((index 0) (best (aref logits 0)))
    (dotimes (i (length logits) index)
      (let ((value (aref logits i)))
        (when (or (sb-ext:float-nan-p value) (sb-ext:float-infinity-p value))
          (error "Nonfinite model logits"))
        (when (> value best) (setf best value index i))))))
(defun generate (session prompt &key (max-tokens 32) (chat nil) system)
  (unless (and (integerp max-tokens) (>= max-tokens 0)) (error "Invalid output-token limit"))
  (when (and system (not chat)) (error "A system message requires chat mode"))
  (bt:with-lock-held ((session-lock session))
    (ensure-session-open session)
    (let* ((model (session-model session)) (tokenizer (model-tokenizer model))
           (input (if (stringp prompt)
                      (tokenize-with tokenizer (if chat (chat-prompt prompt :system system) prompt) chat)
                      (progn (when chat (error "Chat requires a string prompt")) (coerce prompt 'vector))))
           (out (make-array 0 :element-type '(unsigned-byte 32) :adjustable t :fill-pointer 0)))
      (unless (plusp (length input)) (error "Prompt must contain at least one token"))
      (when (> (+ (length input) (max 0 (1- max-tokens))) (session-context session))
        (error "Prompt and requested output exceed session context"))
      (map nil (lambda (id)
                 (unless (and (integerp id) (<= 0 id) (< id (length (tokenizer-tokens tokenizer))))
                   (error "Invalid prompt token ID ~A" id))) input)
      (%reset-session session)
      ;; TODO (#133): batch-size-one prefill; use blocked GEMM for long prompts.
      (map nil (lambda (token) (%step! session token)) input)
      (dotimes (i max-tokens)
        (let ((token (greedy-token (session-logits session))))
          (when (member token (tokenizer-eos tokenizer)) (return))
          (vector-push-extend token out)
          (when (< i (1- max-tokens)) (%step! session token))))
      (let ((ids (coerce out '(simple-array (unsigned-byte 32) (*)))))
        (values ids (detokenize-with tokenizer ids nil))))))
