(in-package #:cl-qwen)

(defstruct tokenizer tokens bytes ids merges encoder specials special-scanner scanner bos eos)
(defun byte-encoder ()
  (let ((out (make-array 256)) (extra 256))
    (dotimes (i 256 out)
      (setf (aref out i)
            (code-char (if (or (<= 33 i 126) (<= 161 i 172) (<= 174 i 255)) i
                           (prog1 extra (incf extra))))))))
(defun build-tokenizer (metadata)
  (unless (and (equal (gethash "tokenizer.ggml.model" metadata) "gpt2")
               (equal (gethash "tokenizer.ggml.pre" metadata) "qwen2"))
    (error "Only Qwen byte-level BPE (gpt2/qwen2) is supported"))
  (let* ((tokens (gethash "tokenizer.ggml.tokens" metadata))
         (types (gethash "tokenizer.ggml.token_type" metadata))
         (merges (gethash "tokenizer.ggml.merges" metadata))
         (encoder (byte-encoder)) (decoder (make-hash-table))
         (ids (make-hash-table :test 'equal)) (ranks (make-hash-table :test 'equal))
         (specials (make-hash-table :test 'equal)) (bytes (make-array (length tokens))))
    (unless (and (vectorp tokens) (vectorp types) (= (length tokens) (length types)) (vectorp merges))
      (error "Incomplete BPE metadata"))
    (dotimes (i 256) (setf (gethash (aref encoder i) decoder) i))
    (dotimes (i (length tokens))
      (let ((token (aref tokens i)))
        (unless (stringp token) (error "Invalid tokenizer token"))
        (setf (gethash token ids) i)
        (if (member (aref types i) '(3 4))
            (setf (gethash token specials) i (aref bytes i) (babel:string-to-octets token :encoding :utf-8))
            (setf (aref bytes i)
                  (map '(simple-array (unsigned-byte 8) (*))
                       (lambda (c) (or (gethash c decoder) (error "Invalid BPE byte character ~S" c))) token)))))
    (dotimes (i (length merges)) (setf (gethash (aref merges i) ranks) i))
    (let* ((names (sort (loop for key being the hash-keys of specials collect key) #'> :key #'length))
           (special-scanner (when names
                              (cl-ppcre:create-scanner
                               (format nil "~{~A~^|~}" (mapcar #'cl-ppcre:quote-meta-chars names)))))
           (bos (gethash "tokenizer.ggml.bos_token_id" metadata))
           (eos (remove-duplicates
                 (remove nil (list (gethash "tokenizer.ggml.eos_token_id" metadata)
                                   (gethash "<|im_end|>" ids) (gethash "<|endoftext|>" ids))))))
      (dolist (id (cons bos eos))
        (when (and id (not (and (integerp id) (<= 0 id) (< id (length tokens)))))
          (error "Invalid special token ID ~A" id)))
      (make-tokenizer
       :tokens tokens :bytes bytes :ids ids :merges ranks :encoder encoder :specials specials
       :special-scanner special-scanner :bos (and (gethash "tokenizer.ggml.add_bos_token" metadata) bos) :eos eos
       :scanner (cl-ppcre:create-scanner
                 "(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+")))))

(defun candidate-less-p (a b)
  (or (< (first a) (first b)) (and (= (first a) (first b)) (< (second a) (second b)))))
(defun heap-push (heap item)
  (vector-push-extend item heap)
  (loop for child = (1- (length heap)) then parent
        for parent = (floor (1- child) 2)
        while (and (> child 0) (candidate-less-p (aref heap child) (aref heap parent)))
        do (rotatef (aref heap child) (aref heap parent))))
(defun heap-pop (heap)
  (let ((out (aref heap 0)) (last (vector-pop heap)))
    (when (plusp (length heap))
      (setf (aref heap 0) last)
      (loop with n = (length heap) for parent = 0 then child
            for left = (1+ (* parent 2)) for right = (1+ left)
            while (< left n)
            for child = (if (and (< right n) (candidate-less-p (aref heap right) (aref heap left))) right left)
            while (candidate-less-p (aref heap child) (aref heap parent))
            do (rotatef (aref heap parent) (aref heap child))))
    out))
(defun bpe-piece (tokenizer text output)
  (let* ((octets (babel:string-to-octets text :encoding :utf-8)) (n (length octets))
         (pieces (map 'vector (lambda (x) (string (aref (tokenizer-encoder tokenizer) x))) octets))
         (next (make-array n)) (previous (make-array n))
         (versions (make-array n :initial-element 0)) (active (make-array n :initial-element t))
         (heap (make-array 0 :adjustable t :fill-pointer 0)))
    (dotimes (i n) (setf (aref next i) (if (= i (1- n)) -1 (1+ i)) (aref previous i) (1- i)))
    (labels ((offer (left)
               (when (>= left 0)
                 (let ((right (aref next left)))
                   (when (>= right 0)
                     (let ((rank (gethash (concatenate 'string (aref pieces left) " " (aref pieces right))
                                          (tokenizer-merges tokenizer))))
                       (when rank
                         (heap-push heap (list rank left right (aref versions left) (aref versions right))))))))))
      (dotimes (i n) (offer i))
      (loop while (plusp (length heap))
            do (destructuring-bind (rank left right lv rv) (heap-pop heap)
                 (declare (ignore rank))
                 (when (and (aref active left) (aref active right) (= (aref next left) right)
                            (= (aref versions left) lv) (= (aref versions right) rv))
                   (setf (aref pieces left) (concatenate 'string (aref pieces left) (aref pieces right))
                         (aref active right) nil (aref next left) (aref next right))
                   (incf (aref versions left))
                   (when (>= (aref next right) 0) (setf (aref previous (aref next right)) left))
                   (offer (aref previous left)) (offer left)))))
    (loop for i = 0 then (aref next i) while (and (< i n) (>= i 0))
          do (vector-push-extend (or (gethash (aref pieces i) (tokenizer-ids tokenizer))
                                    (error "BPE result is absent from vocabulary")) output))))
(defun encode-text (tokenizer text output)
  (let ((position 0))
    (cl-ppcre:do-matches (start end (tokenizer-scanner tokenizer) text)
      (unless (= start position) (error "Pretokenizer skipped text at ~D" position))
      (bpe-piece tokenizer (subseq text start end) output)
      (setf position end))
    (unless (= position (length text)) (error "Pretokenizer did not consume input"))))
(defun tokenize-with (tokenizer text specialp)
  (check-type text string)
  (let ((out (make-array 0 :element-type '(unsigned-byte 32) :fill-pointer 0 :adjustable t)) (position 0))
    (when (tokenizer-bos tokenizer) (vector-push-extend (tokenizer-bos tokenizer) out))
    (when (and specialp (tokenizer-special-scanner tokenizer))
      (cl-ppcre:do-matches (start end (tokenizer-special-scanner tokenizer) text)
        (encode-text tokenizer (subseq text position start) out)
        (vector-push-extend (gethash (subseq text start end) (tokenizer-specials tokenizer)) out)
        (setf position end)))
    (encode-text tokenizer (subseq text position) out)
    (coerce out '(simple-array (unsigned-byte 32) (*)))))
(defun detokenize-with (tokenizer ids specialp)
  (let ((out (make-array 0 :element-type '(unsigned-byte 8) :fill-pointer 0 :adjustable t)))
    (map nil (lambda (id)
               (unless (and (integerp id) (<= 0 id) (< id (length (tokenizer-tokens tokenizer))))
                 (error "Invalid token ID ~A" id))
               (unless (and (not specialp) (gethash (aref (tokenizer-tokens tokenizer) id) (tokenizer-specials tokenizer)))
                 (map nil (lambda (byte) (vector-push-extend byte out)) (aref (tokenizer-bytes tokenizer) id)))) ids)
    (babel:octets-to-string out :encoding :utf-8 :errorp nil)))
(defun chat-prompt (user &key system)
  (check-type user string)
  (when system (check-type system string))
  (format nil "~@[<|im_start|>system~%~A<|im_end|>~%~]<|im_start|>user~%~A<|im_end|>~%<|im_start|>assistant~%<think>~%~%</think>~%~%"
          system user))
